# Generated by Django 3.2.6 on 2021-09-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('affect_kr', models.CharField(max_length=140)),
                ('affect_en', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('des_source', models.CharField(max_length=140)),
                ('definition', models.TextField()),
                ('def_source', models.CharField(max_length=140)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
