# Generated by Django 3.2.6 on 2021-09-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affect',
            name='def_source',
        ),
    ]
