# Generated by Django 3.2.6 on 2021-09-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affects', '0002_remove_affect_def_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affect',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
