# Generated by Django 3.2.6 on 2021-09-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210904_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='qvlink_1',
            new_name='netflix_link',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='qvlink_2',
            new_name='tving_link',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='qvlink_3',
            new_name='watcha_link',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='qvlink_4',
            new_name='wavve_link',
        ),
    ]
